spring.application.name=demo

# 1. DB ?? ?? (??? ? ??)
spring.datasource.url=jdbc:postgresql://localhost:5432/steamgg_PostgreSQL
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:dlrudalswns2@}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA/Hibernate ??
# update: ??? ???(Java)? DB ??? ??? ???? ???
spring.jpa.hibernate.ddl-auto=update
# ???? ?? ???? SQL?? ??? ??? (????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. PostgreSQL ?? (??? ?? ?? ???)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 4. ?? ?? ??
server.port=8080